version: '3'
services:
  qdrant:
    image: qdrant/qdrant:v1.9.1
    volumes:
      - ./qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
  api:
    build: ./api
    environment:
      - QDRANT_COLLECTION=bahai-crossrefs
      - QDRANT_URL=http://qdrant:6333
      - EMBED_MODEL=intfloat/e5-large-v2
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
